<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DndPlatform.Application\DndPlatform.Application.csproj" />
    <ProjectReference Include="..\DndPlatform.Persistence\DndPlatform.Persistence.csproj" />
  </ItemGroup>
</Project>
