// <auto-generated />

using System;
using DndPlatform.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DndPlatform.Persistence.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DndPlatform.Persistence.Models.Character", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<int>("Agility")
                    .HasColumnType("integer");

                b.Property<int>("Charisma")
                    .HasColumnType("integer");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("GameId")
                    .HasColumnType("uuid");

                b.Property<int>("Hp")
                    .HasColumnType("integer");

                b.Property<int>("Intelligence")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Physique")
                    .HasColumnType("integer");

                b.Property<int>("Power")
                    .HasColumnType("integer");

                b.Property<string>("Race")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<int>("Wisdom")
                    .HasColumnType("integer");

                b.HasKey("Id")
                    .HasName("Characters_pkey");

                b.HasIndex("GameId");

                b.HasIndex(new[] { "UserId", "GameId" }, "IX_Characters_UserId_GameId");

                b.ToTable("Characters");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.CharacterTemplate", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<int>("Agility")
                    .HasColumnType("integer");

                b.Property<int>("Charisma")
                    .HasColumnType("integer");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("GenderId")
                    .HasColumnType("uuid");

                b.Property<int>("Hp")
                    .HasColumnType("integer");

                b.Property<int>("Intelligence")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Physique")
                    .HasColumnType("integer");

                b.Property<int>("Power")
                    .HasColumnType("integer");

                b.Property<string>("Race")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<int>("Wisdom")
                    .HasColumnType("integer");

                b.HasKey("Id")
                    .HasName("CharacterTemplates_pkey");

                b.HasIndex(new[] { "GenderId" }, "IX_CharacterTemplates_GenderId");

                b.HasIndex(new[] { "UserId" }, "IX_CharacterTemplates_UserId");

                b.ToTable("CharacterTemplates");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Chat", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("GameId")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("Chats_pkey");

                b.HasIndex(new[] { "GameId" }, "IX_Chats_GameId");

                b.ToTable("Chats");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.FavoriteTemplate", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("TemplateId")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("FavoriteTemplates_pkey");

                b.HasIndex("TemplateId");

                b.HasIndex(new[] { "UserId", "TemplateId" }, "IX_FavoriteTemplates_UserId_TemplateId")
                    .IsUnique();

                b.ToTable("FavoriteTemplates");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Game", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("GameStatusId")
                    .HasColumnType("uuid");

                b.Property<Guid>("MasterId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TemplateId")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("Games_pkey");

                b.HasIndex(new[] { "GameStatusId" }, "IX_Games_GameStatusId");

                b.HasIndex(new[] { "MasterId" }, "IX_Games_MasterId");

                b.HasIndex(new[] { "TemplateId" }, "IX_Games_TemplateId");

                b.ToTable("Games");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.GameStatus", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("GameStatuses_pkey");

                b.HasIndex(new[] { "Code" }, "GameStatuses_Code_key")
                    .IsUnique();

                b.ToTable("GameStatuses");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Gender", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("Genders_pkey");

                b.HasIndex(new[] { "Code" }, "Genders_Code_key")
                    .IsUnique();

                b.ToTable("Genders");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Genre", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("Genres_pkey");

                b.HasIndex(new[] { "Code" }, "Genres_Code_key")
                    .IsUnique();

                b.ToTable("Genres");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Master", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("Masters_pkey");

                b.ToTable("Masters");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Message", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<Guid>("ChatId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("SenderTypeId")
                    .HasColumnType("uuid");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("Messages_pkey");

                b.HasIndex(new[] { "ChatId" }, "IX_Messages_ChatId");

                b.HasIndex(new[] { "SenderTypeId" }, "IX_Messages_SenderTypeId");

                b.HasIndex(new[] { "UserId" }, "IX_Messages_UserId");

                b.ToTable("Messages");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.News", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("Arcticle")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("News_pkey");

                b.ToTable("News");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.SenderType", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("SenderTypes_pkey");

                b.HasIndex(new[] { "Code" }, "SenderTypes_Code_key")
                    .IsUnique();

                b.ToTable("SenderTypes");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Template", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Desription")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool?>("IsPublic")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RedFlag")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Setting")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("Templates_pkey");

                b.ToTable("Templates");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.TemplatesGenre", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("GenreId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TemplateId")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("TemplatesGenres_pkey");

                b.HasIndex(new[] { "GenreId" }, "IX_GameGenres_GenreId");

                b.HasIndex(new[] { "TemplateId" }, "IX_GameGenres_TemplateId");

                b.ToTable("TemplatesGenres");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<decimal>("Balance")
                    .HasColumnType("numeric");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Login")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id")
                    .HasName("Users_pkey");

                b.HasIndex(new[] { "Email" }, "Users_Email_key")
                    .IsUnique();

                b.HasIndex(new[] { "Login" }, "Users_Login_key")
                    .IsUnique();

                b.ToTable("Users");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.UsersGame", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("DateCreate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateUpdate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("GameId")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id")
                    .HasName("UsersGames_pkey");

                b.HasIndex(new[] { "GameId" }, "IX_UsersGames_GameId");

                b.HasIndex(new[] { "UserId" }, "IX_UsersGames_UserId");

                b.ToTable("UsersGames");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Character", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.Game", "Game")
                    .WithMany("Characters")
                    .HasForeignKey("GameId")
                    .IsRequired()
                    .HasConstraintName("Characters_GameId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.User", "User")
                    .WithMany("Characters")
                    .HasForeignKey("UserId")
                    .IsRequired()
                    .HasConstraintName("Characters_UserId_fkey");

                b.Navigation("Game");

                b.Navigation("User");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.CharacterTemplate", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.Gender", "Gender")
                    .WithMany("CharacterTemplates")
                    .HasForeignKey("GenderId")
                    .IsRequired()
                    .HasConstraintName("CharacterTemplates_GenderId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.User", "User")
                    .WithMany("CharacterTemplates")
                    .HasForeignKey("UserId")
                    .IsRequired()
                    .HasConstraintName("CharacterTemplates_UserId_fkey");

                b.Navigation("Gender");

                b.Navigation("User");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Chat", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.Game", "Game")
                    .WithMany("Chats")
                    .HasForeignKey("GameId")
                    .IsRequired()
                    .HasConstraintName("Chats_GameId_fkey");

                b.Navigation("Game");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.FavoriteTemplate", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.Template", "Template")
                    .WithMany("FavoriteTemplates")
                    .HasForeignKey("TemplateId")
                    .IsRequired()
                    .HasConstraintName("FavoriteTemplates_TemplateId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.User", "User")
                    .WithMany("FavoriteTemplates")
                    .HasForeignKey("UserId")
                    .IsRequired()
                    .HasConstraintName("FavoriteTemplates_UserId_fkey");

                b.Navigation("Template");

                b.Navigation("User");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Game", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.GameStatus", "GameStatus")
                    .WithMany("Games")
                    .HasForeignKey("GameStatusId")
                    .HasConstraintName("Games_GameStatusId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.Master", "Master")
                    .WithMany("Games")
                    .HasForeignKey("MasterId")
                    .IsRequired()
                    .HasConstraintName("Games_MasterId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.Template", "Template")
                    .WithMany("Games")
                    .HasForeignKey("TemplateId")
                    .IsRequired()
                    .HasConstraintName("Games_TemplateId_fkey");

                b.Navigation("GameStatus");

                b.Navigation("Master");

                b.Navigation("Template");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Message", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.Chat", "Chat")
                    .WithMany("Messages")
                    .HasForeignKey("ChatId")
                    .IsRequired()
                    .HasConstraintName("Messages_ChatId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.SenderType", "SenderType")
                    .WithMany("Messages")
                    .HasForeignKey("SenderTypeId")
                    .IsRequired()
                    .HasConstraintName("Messages_SenderTypeId_fkey");

                b.Navigation("Chat");

                b.Navigation("SenderType");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.TemplatesGenre", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.Genre", "Genre")
                    .WithMany("TemplatesGenres")
                    .HasForeignKey("GenreId")
                    .IsRequired()
                    .HasConstraintName("TemplatesGenres_GenreId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.Template", "Template")
                    .WithMany("TemplatesGenres")
                    .HasForeignKey("TemplateId")
                    .IsRequired()
                    .HasConstraintName("TemplatesGenres_TemplateId_fkey");

                b.Navigation("Genre");

                b.Navigation("Template");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.UsersGame", b =>
            {
                b.HasOne("DndPlatform.Persistence.Models.Game", "Game")
                    .WithMany("UsersGames")
                    .HasForeignKey("GameId")
                    .IsRequired()
                    .HasConstraintName("UsersGames_GameId_fkey");

                b.HasOne("DndPlatform.Persistence.Models.User", "User")
                    .WithMany("UsersGames")
                    .HasForeignKey("UserId")
                    .IsRequired()
                    .HasConstraintName("UsersGames_UserId_fkey");

                b.Navigation("Game");

                b.Navigation("User");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Chat",
                b => { b.Navigation("Messages"); });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Game", b =>
            {
                b.Navigation("Characters");

                b.Navigation("Chats");

                b.Navigation("UsersGames");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.GameStatus",
                b => { b.Navigation("Games"); });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Gender",
                b => { b.Navigation("CharacterTemplates"); });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Genre",
                b => { b.Navigation("TemplatesGenres"); });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Master",
                b => { b.Navigation("Games"); });

            modelBuilder.Entity("DndPlatform.Persistence.Models.SenderType",
                b => { b.Navigation("Messages"); });

            modelBuilder.Entity("DndPlatform.Persistence.Models.Template", b =>
            {
                b.Navigation("FavoriteTemplates");

                b.Navigation("Games");

                b.Navigation("TemplatesGenres");
            });

            modelBuilder.Entity("DndPlatform.Persistence.Models.User", b =>
            {
                b.Navigation("CharacterTemplates");

                b.Navigation("Characters");

                b.Navigation("FavoriteTemplates");

                b.Navigation("UsersGames");
            });
#pragma warning restore 612, 618
        }
    }
}
