<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Engine.Domain\Engine.Domain.csproj" />
    <ProjectReference Include="..\Engine.Application\Engine.Application.csproj" />
    <ProjectReference Include="..\Engine.Infrastructure\Engine.Infrastructure.csproj" />
    <ProjectReference Include="..\Engine.VectorDBContext\Engine.VectorDBContext.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\Chats\" />
  </ItemGroup>
 </Project>
